default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci

    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
    )

    match(
      type: "appstore",
      app_identifier: "com.votrite.ios",
      api_key: api_key,
      readonly: false,
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Runner.xcodeproj",
      team_id: ENV["TEAM_ID"],
      bundle_identifier: "com.votrite.ios",
      code_sign_identity: "iPhone Distribution",
      profile_name: ENV["sigh_com.votrite.ios_appstore_profile-name"],
    )

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      output_name: "VotRite.ipa",
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
    )
  end
end
